package com.epam.task4.command;

public enum XMLCommandType {
    TO_MAIN_PAGE_COMMAND,
    PARSE_COMMAND,
    AUTHORIZATION_COMMAND,
    REGISTRATION_COMMAND,
    TO_REGISTRATION_PAGE_COMMAND,
    LOG_OUT_COMMAND
}
